name: PEGASUS Project CI
on: 
  push: 
    banches: [ master ]
  pull_request:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: Use Node.js version 17
        uses: actions/setup-node@v2
        with: 
          node-version: '17'
      - run: npm install
      - run: npm run build --prefix client